Title:			Estratégias de Trading  
Subtitle:		  
Author:			Wilson N. de Freitas  
Affiliation:	http://aboutwilson.net  
Date:			October 28, 2012  
Copyright:		2012 Wilson.  
				This work is licensed under a Creative Commons License.  
				http://creativecommons.org/licenses/by-sa/2.5/  
Keywords:		trading strategies, risk, return, CAPM, trading, time series
CSS:			practice.css 


# Atividade 1 - Análise estatística

Usando dados diários e mensais de retornos das séries:

- IBM: [diária](IBM-1962-1994.daily.csv), [mensal](IBM-1962-1994.monthly.csv)
- S&P 500: [diária](GSPC-1962-1994.daily.csv), [mensal](GSPC-1962-1994.monthly.csv)

de 03/jan/1962 a 31/dez/1994, calcule as seguintes análises estatísticas. 

## Estatísticas em retornos simples

Para as séries diárias de retornos simples calcule:

- média
- desvio padrão
- autocorrelação de primeira ordem (lag 1)

Divida as séries em 4 períodos com a mesma quantidade de dados e calcule as mesmas estatísticas para cada sub-período - o que se observa? as medidas permanecem constantes ao longo do tempo?
Faça a mesma análise para retornos compostos - as medidas mudam substancialmente?

## Histogramas

Faça um histograma com as séries diárias de retornos de todo o período da amostra.
Faça agora o gráfico da densidade de probabilidade da distribuição normal com a média e o desvio padrão das séries de retornos.
Os dados *parecem* normais?
Faça a mesma análise para os retornos diários compostos e compare os resultados.

## Boxplot

Usando as séries diárias de retornos simples construa o boxplot para toda a amostra e para os 4 sub-períodos.
Há algum deslocamento?
Faça a análise novamente para os retornos compostos.

## Assimetria e kurtose

Usando as séries diárias calcule assimetria e kurtose para os retornos simples e compostos para todo o período da amostra e para os 4 sub-períodos.
Estas estatísticas são constantes no tempo?

## Dados mensais

Refaça as análises anteriores para dados mensais e compare os resultados.
Qual a conclusão sobre a normalidade destes dados?



<br/><br/><br/><br/><br/><br/>